name: ponyc update breakage test

on:
  repository_dispatch:
    types: [shared-docker-linux-builders-updated]

jobs:
  vs-ponyc-latest:
    name: Test against ponyc main
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-x86-64-x86-64-unknown-linux-builder:latest
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: make test config=debug
